spring:
  application:
    name: futbol-market
  profiles:
    default: local
  jpa:
    open-in-view: false

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info